In [10]:
import pandas as pd

df=pd.read_csv("/Users/Admin/Desktop/Python30/30-Days-Of-Python/data/hacker_news.csv")
df.columns

Index(['id', 'title', 'url', 'num_points', 'num_comments', 'author',
       'created_at'],
      dtype='object')

In [21]:
df.head(5)

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

In [22]:
df.tail(5)

,id,title,url,num_points,num_comments,author,created_at
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

In [33]:
df['title']

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: object

In [34]:
df.shape

(20099, 7)

In [35]:
df[df['title'].str.contains('python')]

,id,title,url,num_points,num_comments,author,created_at
765,12117140,IronPython 3 (python for .net) development res...,https://www.reddit.com/r/Python/comments/4tbhw...,3,1,tanlermin,7/18/2016 18:34
6129,10512775,Learn data science in python by taking online ...,http://www.dezyre.com/data-science-in-python/36,1,1,shankar251289,11/5/2015 11:34
6711,11328646,"Show HN: Dplython, dplyr data manipulation for...",https://github.com/dodger487/dplython,11,1,capybara,3/21/2016 15:18
7979,10993953,Kickstarter for funding Micropython port to ES...,https://www.kickstarter.com/projects/214379695...,98,41,Sfabris,1/29/2016 7:16
13218,12095313,DQN for Beginners in 200 lines of python code ...,https://yanpanlau.github.io/2016/07/10/FlappyB...,5,1,yanpanlau,7/14/2016 16:40
13575,11269629,Show HN: Venv2docker create a docker image fr...,https://github.com/Markbnj/venv2docker,8,2,markbnj,3/11/2016 21:20
14004,12200724,EasyMake one python file instead tons of Make...,https://github.com/l4l/EasyMake,1,3,kitsu,8/1/2016 7:29
15784,11008512,let in python (2014),https://nvbn.github.io/2014/09/25/let-statemen...,1,2,hatmatrix,1/31/2016 22:43
16026,12238517,Ptpython better than ipython or bpython?,http://terriblecode.com/why-ptpython-is-the-on...,1,1,ausjke,8/6/2016 15:55
18421,12027874,Show HN: Stack overflow command line client ad...,https://github.com/gautamkrishnar/socli,1,1,gautamkrishnar,7/3/2016 22:12
18809,11191696,The origins of the class Meta idiom in python,http://mapleoin.github.io/perma/python-class-meta,6,1,mapleoin,2/28/2016 18:09
19356,10593520,Crypto and SSL toolkit for python (M2Crypto),https://gitlab.com/m2crypto/m2crypto,1,1,kevindeasis,11/19/2015 8:41

In [36]:
df[df['title'].str.contains('JavaScript')]

,id,title,url,num_points,num_comments,author,created_at
267,12352636,Show HN: Hire JavaScript - Top JavaScript Talent,https://www.hirejs.com/,1,1,eibrahim,8/24/2016 15:16
811,10741251,Ask HN: Are there any projects or compilers wh...,NaN,1,2,ggonweb,12/15/2015 23:26
1046,11343334,"If you write JavaScript tools or libraries, bu...",https://medium.com/@Rich_Harris/how-to-not-bre...,48,19,callumlocke,3/23/2016 10:54
1093,10422726,Rollup.js: A next-generation JavaScript module...,http://rollupjs.org,57,17,dmmalam,10/21/2015 0:02
1162,12461624,V8 JavaScript Engine: V8 Release 5.4,http://v8project.blogspot.com/2016/09/v8-relea...,126,19,okket,9/9/2016 12:46
...,...,...,...,...,...,...,...
19349,11448301,"Fotorama, a responsive JavaScript photo gallery",http://fotorama.io/,1,1,alexkon,4/7/2016 15:59
19548,12105148,Another Kind of JavaScript Fatigue,http://chrismm.com/blog/the-other-kind-of-java...,9,2,JacksCracked,7/16/2016 3:44
19610,12203508,Lonely programmer detective uncovers the Mozil...,http://stackoverflow.com/a/38677222/984780,29,8,luisperezphd,8/1/2016 16:07
19885,12552131,Ask HN: Best Practices for CSS in a Modern Jav...,NaN,6,6,xwvvvvwx,9/21/2016 20:53
20069,12149183,Show HN: Parse recipe ingredients using JavaSc...,https://github.com/herkyl/ingredients-parser,6,2,zongitsrinzler,7/23/2016 11:35

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20099 entries, 0 to 20098
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20099 non-null  int64
 1   title         20099 non-null  object
 2   url           17659 non-null  object
 3   num_points    20099 non-null  int64
 4   num_comments  20099 non-null  int64
 5   author        20099 non-null  object
 6   created_at    20099 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.1+ MB